replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "2Gi"
    cpu: "2"
    ephemeralStorage: "500M"
    nvidiaGPU: "0"
  limits:
    memory: "4Gi"
    cpu: "3"
    ephemeralStorage: "1000M"
    nvidiaGPU: "0"

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
